# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReadTextLinesWithCameraEnhancerObjc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReadTextLinesWithCameraEnhancerObjc
  pod 'DynamsoftCore', '3.0.20'
  pod 'DynamsoftLicense', '3.0.30'
  pod 'DynamsoftUtility', '1.0.21'
  pod 'DynamsoftCameraEnhancer', '4.0.2'
  pod 'DynamsoftCaptureVisionRouter', '2.0.21'
  pod 'DynamsoftImageProcessing', '2.0.21'
  pod 'DynamsoftLabelRecognizer', '3.0.20'

end
